### ISSUE TITLE
AWS_PROFILE not found

### ISSUE THREAD

**Issue by ruzickap** [VioletCranberry/kubectl-node-ssm#4]
Hello.

I'm using the following variables to connect to AWS account: `AWS_ACCESS_KEY_ID`,  `AWS_SECRET_ACCESS_KEY`, `AWS_ROLE_ARN`, `AWS_SESSION_TOKEN`

I'm not using AWS config file or `AWS_PROFILE` - that is the reason why I'm getting the following error:

```bash
# kubectl node-ssm start-session --target ip-192-168-1-1.ec2.internal
panic: can't parse AWS_PROFILE from []
...
```

For example the command `aws ec2 describe-images --query 'Images[*].[ImageId]' --region eu-central-1` is working fine without the `AWS_PROFILE`...

Can it be fixed?

Thank you...

**Comment by VioletCranberry** [comment]
Hey @ruzickap can you please run `aws eks update-kubeconfig --region region-code --name my-cluster` and run the plugin again? I am referring to the notes section here https://github.com/VioletCranberry/kubectl-node-ssm#notes - you might need to run the command with `--profile` so the new generated EKS config would include `AWS_PROFILE` as it is missing as a part of ENV additional environment variables to expose to the process, and hence you're getting an error.

**Comment by VioletCranberry** [comment]
In addition to the above, it seems that the AWS SDK does not have a default Region, so you might need to set the variable anyway, then regenerating the EKS config to have the `AWS_PROFILE` exposed there.

**Comment by VioletCranberry** [comment]
Actually, give me a moment to think about it. And sorry for a late reply, by the way :)

**Comment by ruzickap** [comment]
Thanks for looking at it.
I run the suggested command:

```bash
❯ aws eks update-kubeconfig --region us-east-1 --name=k01 --kubeconfig /tmp/test
❯ cat /tmp/test

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0xxxxxxxxxxtCg==
    server: https://8xxxxxxxxxxx25.gr7.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
    user: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
  name: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
current-context: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:7xxxxxxxxxxx7:cluster/k01
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - k01
      - --output
      - json
      command: aws
```

I also tried to run the `aws ssm start-session --target <instance id>` which is working fine:

```bash
❯ kubectl get nodes -o yaml | grep providerID
    providerID: aws:///us-east-1a/i-01964e5962b904609
    providerID: aws:///us-east-1a/i-0f3d5c903eab3146d
❯ aws ssm start-session --target i-0f3d5c903eab3146d --region us-east-1


Starting session with SessionId: ruzickap@M-C02DP163ML87-k8s-1xxxxxxxx2-0xxxxxxxxxxxxxxxx6
          Welcome to Bottlerocket's control container!
...
...
...
[ssm-user@control]$ uname -a
Linux ip-192-168-7-92.ec2.internal 5.15.108 #1 SMP Wed May 24 23:46:24 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
```

Then the plugin:

```bash
❯ kubectl get nodes
NAME                            STATUS   ROLES    AGE     VERSION
ip-192-168-6-182.ec2.internal   Ready    <none>   6h37m   v1.25.9-eks-5f89878
ip-192-168-7-92.ec2.internal    Ready    <none>   6h37m   v1.25.9-eks-5f89878

❯ kubectl node-ssm start-session --target ip-192-168-7-92.ec2.internal
panic: can't parse AWS_PROFILE from []
```

Let me know if you need more details...

**Comment by VioletCranberry** [comment]
By default, the SDK checks the `AWS_PROFILE` environment variable to determine which profile to use. If no `AWS_PROFILE` variable is set, the SDK uses the `default` profile. So it seems you are running everything under `default` profile. 

The Session will attempt to load configuration and credentials from the environment, configuration files, and other credential sources. The order configuration is loaded in is:

```
1. Environment Variables
2. Shared Credentials file
3. Shared Configuration file (if SharedConfig is enabled)
4. EC2 Instance Metadata (credentials only)
```

So I added a fallback to an AWS session with Shared Configuration file enabled. The biggest problem is that I do not have access to any of the SSM enabled environments right now, so I can only rely on test-driven approach :) 

Would you mind testing the plugin from the branch https://github.com/VioletCranberry/kubectl-node-ssm/tree/trivial-consider-aws-env-vars ?

**Comment by ruzickap** [comment]
Thank you.

I tried the new version from https://github.com/VioletCranberry/kubectl-node-ssm/pull/5 and it is working fine:

```bash
❯ kubectl node-ssm --target "ip-192-168-22-42.ec2.internal"

Starting session with SessionId: ruzickap@M-C02DP163ML87-k8s-1687719293-052045cebe4e14e88
          Welcome to Bottlerocket's control container!
...
...
...
[ssm-user@control]$
```

Please go ahead and merge + release :-)

Thanks a lot...

**Comment by VioletCranberry** [comment]
https://github.com/kubernetes-sigs/krew-index/pull/3215/ v0.0.3 released and available via Krew. Thanks for testing it, @ruzickap :)
